services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=topics
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  app:
    build: .
    ports:
      - 80:80
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_NAME=topics
    depends_on:
      - db
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - app_network

networks:
  app_network: